/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiStep: typeof import('./components/steps/ApiStep.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    EmailStep: typeof import('./components/steps/EmailStep.vue')['default']
    FlowCard: typeof import('./components/FlowCard.vue')['default']
    FlowEditor: typeof import('./components/FlowEditor.vue')['default']
    LogicStep: typeof import('./components/steps/LogicStep.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepCard: typeof import('./components/StepCard.vue')['default']
    StepSidebar: typeof import('./components/StepSidebar.vue')['default']
  }
}
